apiVersion: apps/v1
kind: Deployment
metadata:
  name: tesla-rank
  namespace: tesla
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tesla-rank
  template:
    metadata:
      labels:
        app: tesla-rank
    spec:
      containers:
        - name: tesla-rank
          image: quay.io/rajsinghcpre/tesla-rank:v0.0.3
          ports:
            - containerPort: 80
              name: http
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: postgres-app
                  key: host
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: postgres-app
                  key: port
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-app
                  key: user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-app
                  key: password
            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: postgres-app
                  key: dbname
            - name: DB_CONNECTION
              value: pgsql
            - name: APP_ENV
              value: production
            - name: APP_KEY
              value: base64:chFuYbKKde3+rZAa3MJbZL/Phm4dBwjOuQ+k7DeuW38=
            - name: TWITTER_CLIENT_API_KEY
              value: 5MhDj4mKCkXhEvp598iD3g8LX
            - name: TWITTER_CLIENT_API_SECRET_KEY
              value: tPLcv5NH4qQnljLF6kRx7i1n3G4OmIrZguQN86z2RN0tg2QeIi
            - name: TWITTER_CALLBACK_URL
              value: https://tesla-rank.test/auth/twitter/callback
