apiVersion: v1
kind: Service
metadata:
  name: tesla-rank
  namespace: tesla
  labels:
    app: tesla-rank
spec:
  selector:
    app: tesla-rank
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
